spring.application.name=personal_bussiness_backend_pro
server.port=8081

# spring.datasource.url=jdbc:mysql://localhost:3306/atelier?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
# spring.datasource.username=root
# spring.datasource.password=root

# PostgreSQL - Render
spring.datasource.url=jdbc:postgresql://dpg-d7oucj4m0tmc73dd8i40-a.singapore-postgres.render.com/atelier_xemc
spring.datasource.username=atelier_xemc_user
spring.datasource.password=SuDXAdRaR3Ehvdmyh9lu5Y2Cy0iZAC8x
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.com.raahulsatelier=DEBUG


# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.com.raahulsatelier=DEBUG



# \u2500\u2500 Add these 3 lines to diagnose \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
debug=true
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.security=mySecretKeyForJWTTokenGenerationAtelierStudio2024Key!
jwt.expiration=86400000